{{ if .Values.predictiveScaling }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "calculator-squared.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "calculator-squared.fullname" . }}
  minReplicas: {{ .Values.replicaCount.min }}
  maxReplicas: {{ .Values.replicaCount.max }}
  metrics:
    - type: Pods
      pods:
        metricName: predictive_cpu
        targetAverageValue: 80
{{ else }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "calculator-squared.fullname" . }}
spec:
  minReplicas: {{ .Values.replicaCount.min }}
  maxReplicas: {{ .Values.replicaCount.max }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "calculator-squared.fullname" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
{{ end }}