# Default values for redis-queue.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount:
  max: 1
  min: 1

image: bitnami/redis:latest

service:
  type: ClusterIP
  port: 6379

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 256Mi
