stages:
  - build
  - test
  - push-image
  - deploy
  - verify-deploy

build-image:
  image: docker:19.03.1-dind
  stage: build
  script: docker build . -t $CI_REGISTRY_IMAGE
  tags:
    - dindrunner02
  except:
    - schedules

test:
  image: python:3.6
  stage: test
  script: python3 app/test/testFactorial.py
  except:
    - schedules

lint:
  image: python:3.6
  stage: test
  script:
    - pip3 install pylint
    - pylint app --errors-only
  allow_failure: true
  except:
    - schedules

smoke-test:
  stage: test
  image: qmarketing/dind-docker-compose:18.09.5
  tags:
    - dindrunner02
  script:
    - cd factorial-smoke-test
    - docker-compose down || true
    - docker-compose build api-under-test && docker-compose up -d api-under-test
    - docker-compose build smoke-test && docker-compose run smoke-test
    - docker-compose down
  except:
    - schedules

smoke-lint:
  stage: test
  image: node:13
  script:
    - cd factorial-smoke-test
    - npm i
    - npm run lint
  except:
    - schedules

push-image:
  image: docker:19.03.1-dind
  stage: push-image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
  tags:
    - dindrunner02
  except:
    - schedules

deploy:
  image: dtzar/helm-kubectl
  stage: deploy
  script:
    - mkdir /root/.kube && touch /root/.kube/config
    - echo $KUBER_CONFIG | base64 -d > /root/.kube/config
    - cd calculator-factorial
    - helm upgrade factorial . --namespace calculator-project --wait
  only:
    - master
  except:
    - schedules

verify-deploy:
  stage: verify-deploy
  image: qmarketing/dind-docker-compose:18.09.5
  tags:
    - dindrunner02
  script:
    - cd factorial-smoke-test
    - docker-compose down || true
    - docker-compose build api-under-test && docker-compose up -d api-under-test
    - sleep 5 && docker-compose build verification-test && docker-compose run verification-test
    - docker-compose down
  only:
    - master
  except:
    - schedules

timing-test:
  stage: verify-deploy
  image: qmarketing/dind-docker-compose:18.09.5
  tags:
    - dindrunner02
  script:
    - cd factorial-smoke-test
    - docker-compose down || true
    - docker-compose build api-under-test && docker-compose up -d api-under-test
    - sleep 5 && docker-compose build monitoring-test && docker-compose run monitoring-test
    - docker-compose down
  only:
    - schedules
