# Default values for qis-index-ad-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount:
  max: 5
  min: 1

image: registry.hal.davecutting.uk/jmccartney13/qis-index-ad-api
predictiveScaling: true
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: ads.qis-project.qpc.hal.davecutting.uk
      paths: ["/"]

resources:
  limits:
    cpu: 100m
    memory: 64Mi
