apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qis-index-ad-api.fullname" . }}
  labels:
    pythia.io/enabled: "true"
{{ include "qis-index-ad-api.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.min }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "qis-index-ad-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "qis-index-ad-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        timstamp: "{{ date "20060102150405" .Release.Time }}"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gitlab-creds
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
          env:
            - name: QUEENS_INDEX_URL
              value: "{{ .Release.Name }}-redis-search"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
